### ISSUE TITLE
Nightly Build with Clang / Intel not compiling with intrusive Ptr

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4757]
as the title says
The error is the following: 
`/home/ubuntu/Kratos/external_libraries/intrusive_ptr/intrusive_ptr.hpp:61:13: error: constexpr constructor never produces a constant expression [-Winvalid-constexpr]`

there are also some warnings related to the intrusive ptr:
`/home/ubuntu/Kratos/external_libraries/intrusive_ptr/intrusive_ptr.hpp:468:3: warning: use of this statement in a constexpr function is a C++14 extension [-Wc++14-extensions]`

`/home/ubuntu/Kratos/external_libraries/intrusive_ptr/intrusive_ptr.hpp:473:3: warning: use of this statement in a constexpr function is a C++14 extension [-Wc++14-extensions]`

**Comment by RiccardoRossi** [comment]
yeeeee!

i don't have a recent clang here. could u try to remove the constexpr in line 61?

my goal is to remove very soon this intrusive_ptr implementation in favor of a simpler one which i extracted from boost (getting rid of boost dependencies)
Such implementation is simpler since it does not have weak pointers.

the succession of (admittedly quite large PRs) that i am doing goes in the direction of getting rid of weak pointers so to be able to
1 - use global pointers instead of weak pointers (will allow mpi parallelism)
2 - reducing the memory occupation of each intrusive pointer to 1double (down from the 3 doubles of a shared ptr)

hope to have this done fassssst

**Comment by philbucher** [comment]
I also don't have clang :)
I think the one in the nightly build is quite an old one so I am not sure how important maintaining it is. With newer version I guess it works otherwise more ppl would have complained
what do you think @roigcarlo ?

Maybe we can leave this open and check again after you are done with your updates

**Comment by roigcarlo** [comment]
Ok let me compile it here

**Comment by RiccardoRossi** [comment]
as i understand @rubenzorrilla tried it out, and it compiles on more recent versions of clang. i would propose to leave the bug unresolved for a few days until we change to a simpler version of the intrusive pointer

**Comment by philbucher** [comment]
Makes full sense to me
Lets keep this open as a reminder

**Comment by philbucher** [comment]
Intel is also not compiling with current master 
~~~
Kratos/external_libraries/intrusive_ptr/intrusive_ptr.hpp(470): error: statement may not appear in a constexpr function
  		return *get();
~~~

**Comment by rubenzorrilla** [comment]
Sorry for the late reply. I had this same error with clang 3.8.

**Comment by philbucher** [comment]
This is the last commit that works in case anyone else needs this:
`a444f587cc968fe68d5a541658c821d75cae159e`

**Comment by RiccardoRossi** [comment]
did u try to take out the constexpr?

**Comment by roigcarlo** [comment]
I understand this is fixed now.

**Comment by philbucher** [comment]
Intel compiles again, but not the nightly build

From what I understood this will be looked at after the new version of the intrusive ptr is merged

**Comment by roigcarlo** [comment]
Oh, sorry, I thought #4784 fixed the nightly as well

**Comment by philbucher** [comment]
nah the nightly still fails :
~~~
/home/ubuntu/Kratos/external_libraries/intrusive_ptr/intrusive_ptr.hpp:61:13: error: constexpr constructor never produces a constant expression [-Winvalid-constexpr]
~~~

**Comment by philbucher** [comment]
nightly build works again
